
os:
  - linux
language: python
python:
 - '3.6'
# - "3.7"


install:
- pip install .

script:
  - echo "succesful"



deploy:
  - provider: pypi
    user: phynix
    password:
      secure: "sYaUzRnBXwBLFUCK1Mq7gXcPqcQ91+pGiOvUT8WSsrusK+Td4qvpIDP/fRQTiUkd0x5xXv206smGGjim+JP9xAY2RVDVI+xfxQThxIEH4ne5rDJnq66AR40RW7205MiHOw4kMA39sSrIw4Gxl+H9UOEZBAPOMIFhDRXIdbuc/xBfHbD9J26xynlIqzY3hC+yfz4Aqz/4uSRWmifeYIYEqvy5nfaMNMs3mqqGbCKQ4Wi7QDX4L6Xr2T0VuqoAQs767ftbOFezPWGPJTPB37cNyT4/XgJWhMfiFFAIbqaP82l8qmZga0Bh5EzvaYA/9YcT4HXWUcp/teUbsZfiQKsIuRYPvW2nV43xLGvzwAZ3ur3cAzM4ZAK1NIeWUhfP93/miHiY9H6pyXPqsPVOpYloNbp//atushgrSccLxL12Q4UvorKaJ8DDZAd0uGgDb9zH5JIkfWhP5nxSVFLjeErKDTl5oSv4f81MMmjV2B6ZvI1MXHarOMpsAq7z/51HL+Okt3uoWBFKfVBxAYWHSgZR2p5ewCdzb3DFRsZV+shQu5nWQl01NSIfB56GSkgORpjYdHe8ekCDgUdOK8erLdyQXoHZxiWjHZpD8qTOJsTe0gapMxS5qjM9127HxYvOSh5+UxY8CVxPrEXqR3jKAQaDMOyklOnHZeeizgyWJgSsj4M="
    distributions: sdist bdist_wheel
    on:
      branch: master
      tags: true
      python: 3.6
